# -*- coding: utf-8 -*-
"""scrape.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O7akmOLPy-HsJsPswqCDrdWLmptQ1YKe
"""

import requests
from bs4 import BeautifulSoup

def game(keyword):
  url = "https://store.steampowered.com/search/?term=" + keyword
  headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36'}
  source = requests.get(url, headers=headers)
  soup = BeautifulSoup(source.text, "html.parser")
  span_title = soup.find_all("span", {"class":"title"})
  div_date = soup.find_all("div", {"class":"col search_released responsive_secondrow"})
  div_price = soup.find_all("div", {"class":"col search_price responsive_secondrow"})

  for title,date,price in zip(span_title,div_date,div_price):
    print('Judul Game: ' + title.text)
    print('Tanggal Rilis: ' + date.text)
    print('Harga Game: ' + price.text.strip())

    print()

def drakor(keyword):
  url = "https://dramacool.sr/search?type=drama&keyword=" + keyword
  headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36'}
  source = requests.get(url, headers=headers)
  soup = BeautifulSoup(source.text, "html.parser")
  h3_title = soup.find_all("h3", {"class":"title"})

  for title in h3_title:
    print('Judul Drakor: ' + title.text)

    print()

def anime(keyword):
  url = "https://anikyojin.org/?s=" + keyword
  headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36'}
  source = requests.get(url, headers=headers)
  soup = BeautifulSoup(source.text, "html.parser")
  h2_title = soup.find_all("h2", {"class":"posttitle"})
  div_info = soup.find_all("div", {"class":"info"})

  for title,info in zip(h2_title,div_info):
    print('Judul Anime : ' + title.text)
    ul = info.find("ul")
    li = ul.find_all("li")
    for item in li:
      print(item.text.strip())
    
    print()

def main():
  # result = game("need for speed")

  # result = drakor("man")

  result = anime("shingeki")

if __name__ == '__main__':
  main()